[package]
name = "counter"
publish = false
version = "0.0.0"
edition.workspace = true
authors.workspace = true

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
teatui = { path = "../../teatui" }
