[package]
name = "tabs"
publish = false
version = "0.0.0"
edition.workspace = true
authors.workspace = true

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
strum = "0.27.2"
teatui = { path = "../../teatui" }
