[package]
name = "teatui"
version = "0.1.0"
description = "An elm-like abstraction over Ratatui"
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
thiserror = "2"
